set cursorline
set noswapfile
set nowb
set nobackup
set number
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoread
set hlsearch
set smartcase
set showmatch
set mat=2
set laststatus=2
set guifont=Monaco:h11
set list lcs=trail:·,precedes:«,extends:»,eol:¬,tab:▸\ 
colo elflord
:syntax on
