abbr -a -U -- dev 'cd ~/Projects'
abbr -a -U -- grep 'grep --color=auto'
abbr -a -U -- iex 'iex --erl "-kernel shell_history enabled"'
abbr -a -U -- kube-unset 'kubectl config unset current-context'
abbr -a -U -- mf 'mix format'
abbr -a -U -- mt 'mix test'
abbr -a -U -- mtf 'mix test --failed'
abbr -a -U -- mtw 'mix test --only wip'
abbr -a -U -- weather curl\ -4\ \'http://wttr.in/Porto+Alegre\?m
abbr -a -U -- pbcopy 'xclip -selection clipboard'
abbr -a -U -- pbpaste 'xclip -selection clipboard -o'
