abbr -a -- dev 'cd ~/Projects'
abbr -a -- grep 'grep --color=auto'
abbr -a -- iex 'iex --erl "-kernel shell_history enabled"'
abbr -a -- kube-unset 'kubectl config unset current-context'
abbr -a -- mf 'mix format'
abbr -a -- mt 'mix test'
abbr -a -- mtf 'mix test --failed'
abbr -a -- mtw 'mix test --only wip'
abbr -a -- weather curl\ -4\ \'http://wttr.in/Porto+Alegre\?m\'
